### ISSUE TITLE
[WG] Discuss WG & project meetings (frequency, duration, attendees)

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/policy_wg#18]
- Bi-weekly WG meetings - 60 minutes (all the WG members)
- Weekly project meetings - 60 minutes (Asim, Anita + Tamara, Zane, researcher and anyone else who has time to join)

**Comment by jawache** [comment]
This sounds good to me.

Given there is a more in-depth weekly meeting I might even suggest to make the bi-weekly 30 mins, esp since so much will be async.

**Comment by holanita** [comment]
See major milestones and meetings [in this GANTT chart](https://view.monday.com/3205828327-c53ddd26e774008fc5a4c6a55a76058c?r=use1).

**Comment by jawache** [comment]
This feels good, should we close this? (it's assigned to me :))

**Comment by holanita** [comment]
Sure
