### ISSUE TITLE
[WG] Discuss logo options

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/policy_wg#20]
Proposal: [see here](https://drive.google.com/file/d/1-LNyFDNK2ZVNlFk03mFvi_ab4rrIG1eE/view?usp=sharing) the draft logo for the SoGS project

**Comment by mrchrisadams** [comment]
hi @holanita  - how would you like feedback on this? We can discuss here, or alternatively, I think google drive supports comments too.

Would you let me know? I'll add the feedback accordingly

**Comment by holanita** [comment]
hi @mrchrisadams let's discuss here. thanks!

**Comment by jawache** [comment]
@mrchrisadams we don't have the kind of cycles to have revisions, so at this moment it's a "pick one" option. We can revisit later if we want to fine tune but our designer is flat out on hackathon and then other things.

**Comment by elisezelechowski** [comment]
I prefer v2, but ultimately defer to the group on this one.

**Comment by mrchrisadams** [comment]
V2 for me.

**Comment by holanita** [comment]
Thanks, I'll let our designer know it's V2.
